### ISSUE TITLE
Error when build: 'extern/glutils does not contain a CMakeLists.txt file.'

### ISSUE THREAD

**Issue by mwheelup** [Treecase/SickleEditor#1]
hi Treecase, I am newbie to build from source code, i tried but couldn't build, the following error occurs when i do `cmake ..` step.

```
CMake Error at CMakeLists.txt:39 (add_subdirectory):
  The source directory

    /home/username/SickleEditor/extern/glutils

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/username/SickleEditor/build/CMakeFiles/CMakeOutput.log".
```

Out of curiosity I found this repository, a new editor for GoldSrc seems interesting. Good luck

**Comment by Treecase** [comment]
This error comes from not initializing the git submodules first, I forgot
to add that to the build steps. Try running "git submodule update --init
--recursive" and it should work.
Thanks for trying it out! The project is still in early development, so you
can't actually do any editing yet, but I think that will be the next step
I'll be working on.

**Comment by treecase** [comment]
This error comes from not initializing the git submodules first, I forgot
to add that to the build steps. Try running `git submodule update --init
--recursive` and it should work.

Thanks for trying it out! The project is still in early development, so you
can't actually do any editing yet, but I think that will be the next step
I'll be working on.

**Comment by mwheelup** [comment]
That works, but now the problem is in `cmake --build . ` step.
First error (Solved :+1: ):
```
In file included from /home/username/SickleEditor/src/convexhull/convexhull.cpp:19:
/home/username/SickleEditor/src/convexhull/include/convexhull/convexhull.hpp:22:10: fatal error: glm/glm.hpp: The file or directory does not exist
   22 | #include <glm/glm.hpp>
```

Same with `<glm/ext/scalar_constants.hpp> ` and `<glm/gtc/epsilon.hpp>`, and also in others .cpp files

Solution was add full path to each include:
```
#include </home/username/SickleEditor/extern/glutils/extern/glm/glm/ext/scalar_constants.hpp>
#include </home/username/SickleEditor/extern/glutils/extern/glm/glm/gtc/epsilon.hpp>
#include </home/username/SickleEditor/extern/glutils/extern/glm/glm/glm.hpp>
#include </home/username/SickleEditor/extern/glutils/extern/glm/glm/ext/scalar_constants.hpp>

```

Second error (Unsolved :-1: ): maybe it is a problem with Lua version that I have installed (Lua 5.4.4)
```

[ 31%] Building CXX object src/editor/lua/CMakeFiles/editor-lua.dir/BrushBox_Lua.cpp.o
/home/username/SickleEditor/src/editor/lua/BrushBox_Lua.cpp: In function ‘int dunder_newindex(lua_State*)’:
/home/username/SickleEditor/src/editor/lua/BrushBox_Lua.cpp:54:5: error: ‘lua_getiuservalue’ was not declared in this scope; did you mean ‘lua_getuservalue’?
   54 |     lua_getiuservalue(L, -3, 1);
      |     ^~~~~~~~~~~~~~~~~
      |     lua_getuservalue
/home/username/SickleEditor/src/editor/lua/BrushBox_Lua.cpp: In function ‘int dunder_index(lua_State*)’:
/home/username/SickleEditor/src/editor/lua/BrushBox_Lua.cpp:63:5: error: ‘lua_getiuservalue’ was not declared in this scope; did you mean ‘lua_getuservalue’?
   63 |     lua_getiuservalue(L, 1, 1);
      |     ^~~~~~~~~~~~~~~~~
      |     lua_getuservalue
/home/username/SickleEditor/src/editor/lua/BrushBox_Lua.cpp: In function ‘int lbrushbox_new(lua_State*, Sickle::Editor::BBox*)’:
/home/username/SickleEditor/src/editor/lua/BrushBox_Lua.cpp:147:9: error: ‘lua_newuserdatauv’ was not declared in this scope; did you mean ‘lua_newuserdata’?
  147 |         lua_newuserdatauv(L, sizeof(CLASSNAME *), 1));
      |         ^~~~~~~~~~~~~~~~~
      |         lua_newuserdata
/home/username/SickleEditor/src/editor/lua/BrushBox_Lua.cpp:153:5: error: ‘lua_setiuservalue’ was not declared in this scope; did you mean ‘lua_setuservalue’?
  153 |     lua_setiuservalue(L, -2, 1);
      |     ^~~~~~~~~~~~~~~~~
      |     lua_setuservalue
gmake[2]: *** [src/editor/lua/CMakeFiles/editor-lua.dir/build.make:76: src/editor/lua/CMakeFiles/editor-lua.dir/BrushBox_Lua.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:679: src/editor/lua/CMakeFiles/editor-lua.dir/all] Error 2

```

> Thanks for trying it out! The project is still in early development, so you
> can't actually do any editing yet, but I think that will be the next step
> I'll be working on.

no problem, I'm not a programmer (sadly) but I understand that developing software is a very complex job. Meanwhile I follow the development being a spectator, good luck :+1:

**Comment by treecase** [comment]
Shouldn't be a problem with Lua, I'm using 5.4.4 too. Not sure what's up with that.

**Comment by Adrikikicp** [comment]
Hello, you forgot to update this as Closed

**Comment by treecase** [comment]
I mean technically it was never resolved, but since its so old I guess I probably should.
